
Options in effect for /Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexer.gi:

    ACTION-BLOCK=("/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexer.java","/.","./")

    AST-DIRECTORY="./ast"  AST-TYPE="Ast"  NOATTRIBUTES  NOAUTOMATIC-AST  
    NOBACKTRACK  BYTE  CONFLICTS  
    DAT-DIRECTORY="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/"
    
    DAT-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexerdcl.data"
    
    DCL-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexerdcl.java"
    NODEBUG  
    DEF-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexerdef.java"
    NOEDIT  NOERROR-MAPS  ESCAPE='$'  
    EXPORT-TERMINALS=("/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLParsersym.java","TK_","")
    EXTENDS-PARSETABLE  FACTORY="new "  FILE-PREFIX="ASLKWLexer"  NOFIRST  
    NOFOLLOW  NOGLR  NOGOTO-DEFAULT  
    GRM-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexer.gi"
    
    IMP-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexerimp.java"
    
    INCLUDE-DIRECTORY="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/templates/java;/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java;"
    LALR=1  LEGACY  NOLIST  MARGIN=4  MAX-CASES=1024  NAMES=OPTIMIZED  
    NONT-CHECK  OR_MARKER='|'  
    OUT-DIRECTORY="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/"
    PACKAGE="org.eclipse.imp.asl.parser"  NOPARENT-SAVE  
    PARSETABLE-INTERFACES="lpg.runtime.ParseTable"  PREFIX="Char_"  PRIORITY  
    PROGRAMMING_LANGUAGE=JAVA  
    PRS-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexerprs.java"
    NOQUIET  READ-REDUCE  REMAP-TERMINALS  NOSCOPES  NOSERIALIZE  
    NOSHIFT-DEFAULT  SINGLE-PRODUCTIONS  NOSOFT-KEYWORDS  NOSTATES  SUFFIX=""  
    SYM-FILE="/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexersym.java"
    TAB-FILE="ASLKWLexer.t"  TABLE  TEMPLATE="KeywordTemplateF.gi"  
    TRACE=CONFLICTS  NOVARIABLES  NOVERBOSE  NOVISITOR  VISITOR-TYPE="Visitor"
    WARNINGS  NOXREF  

/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:14:24:14:24:296:296: Warning: The macro "$" is undefined. No substitution made
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:2:5:2:14:16:25: Informative: The terminal DollarSign is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:3:5:3:11:39:45: Informative: The terminal Percent is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:4:5:4:5:59:59: Informative: The terminal _ is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:19:5:19:79:79: Informative: The terminal h is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:23:5:23:83:83: Informative: The terminal j is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:25:5:25:85:85: Informative: The terminal k is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:37:5:37:97:97: Informative: The terminal q is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:47:5:47:107:107: Informative: The terminal v is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:49:5:49:109:109: Informative: The terminal w is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:51:5:51:111:111: Informative: The terminal x is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:5:55:5:55:115:115: Informative: The terminal z is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:5:6:5:121:121: Informative: The terminal A is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:7:6:7:123:123: Informative: The terminal B is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:9:6:9:125:125: Informative: The terminal C is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:11:6:11:127:127: Informative: The terminal D is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:13:6:13:129:129: Informative: The terminal E is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:15:6:15:131:131: Informative: The terminal F is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:17:6:17:133:133: Informative: The terminal G is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:19:6:19:135:135: Informative: The terminal H is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:21:6:21:137:137: Informative: The terminal I is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:23:6:23:139:139: Informative: The terminal J is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:25:6:25:141:141: Informative: The terminal K is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:27:6:27:143:143: Informative: The terminal L is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:29:6:29:145:145: Informative: The terminal M is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:31:6:31:147:147: Informative: The terminal N is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:33:6:33:149:149: Informative: The terminal O is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:35:6:35:151:151: Informative: The terminal P is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:37:6:37:153:153: Informative: The terminal Q is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:39:6:39:155:155: Informative: The terminal R is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:41:6:41:157:157: Informative: The terminal S is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:43:6:43:159:159: Informative: The terminal T is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:45:6:45:161:161: Informative: The terminal U is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:47:6:47:163:163: Informative: The terminal V is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:49:6:49:165:165: Informative: The terminal W is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:51:6:51:167:167: Informative: The terminal X is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:53:6:53:169:169: Informative: The terminal Y is useless.
/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/lpg.generator/include/java/KWLexerMapF.gi:6:55:6:55:171:171: Informative: The terminal Z is useless.


/Users/rmfuhrer/eclipse/workspaces/imp-3.3-release/org.eclipse.imp.asl/src/org/eclipse/imp/asl/parser/ASLKWLexer.gi:39:5:39:11:565:571: Informative: Grammar is  LALR(1).

Number of Terminals: 56
Number of Nonterminals: 1
Number of Productions: 23
Number of Single Productions: 0
Number of Items: 149
Number of States: 91
Number of Shift actions: 89
Number of Goto actions: 1
Number of Shift/Reduce actions: 21
Number of Goto/Reduce actions: 0
Number of Reduce actions: 2
Number of Shift-Reduce conflicts: 0
Number of Reduce-Reduce conflicts: 0

Number of entries in base Action Table: 92
Additional space required for compaction of Action Table: 1.0%

Number of unique terminal states: 91
Number of Shift actions saved by merging: 0
Number of Conflict points saved by merging: 0
Number of Reduce actions saved by merging: 0
Number of Reduce saved by default: 1

Number of entries in Terminal Action Table: 202
Additional space required for compaction of Terminal Table: 2.4%

Actions in Compressed Tables:
     Number of Shifts: 89
     Number of Shift/Reduces: 21
     Number of Gotos: 1
     Number of Goto/Reduces: 0
     Number of Reduces: 1
     Number of Defaults: 1

Parsing Tables storage:
    Storage required for BASE_CHECK: 23 Bytes
    Storage required for BASE_ACTION: 234 Bytes
    Storage required for TERM_CHECK: 262 Bytes
    Storage required for TERM_ACTION: 416 Bytes
